web:
  build: .
  ports:
    - "8001:3000"
  external_links:
    - dockerdb_mysql_1:db
  volumes:
    - /home/vendor/eventor/public/uploads:/usr/src/app/public/uploads
  environment:
    - EVENTOR_DATABASE_HOST=db
    - EVENTOR_BLOG_URL=http://ubuntu.local:8000/tag/eventor/
    - FDBK_URL=
